<div class="content"><section class="title"><div><span class="eyebrow">NOTIFICACIONES</span><h1>CORREO <em>SMTP.</em></h1><p>Configura la cuenta que enviará pedidos pagados y notificaciones del sistema.</p></div></section>
<?php if(!empty($_SESSION['success'])):?><div class="flash success"><?=htmlspecialchars($_SESSION['success']);unset($_SESSION['success']);?></div><?php endif;?><?php if(!empty($_SESSION['error'])):?><div class="flash error"><?=htmlspecialchars($_SESSION['error']);unset($_SESSION['error']);?></div><?php endif;?>
<div class="flow-admin-grid"><form class="panel flow-settings-form" method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><div class="gateway-head email-gateway"><span>@</span><div><h2>SERVIDOR DE CORREO</h2><p>SMTP autenticado para envíos transaccionales.</p></div><em class="gateway-state <?=!empty($settings['active'])?'online':'offline'?>"><?=!empty($settings['active'])?'ACTIVO':'INACTIVO'?></em></div>
<label class="switch-row"><span><b>USAR SMTP PARA LOS ENVÍOS</b><small>Los correos de pedidos se enviarán desde esta cuenta.</small></span><input type="checkbox" name="active" <?=!empty($settings['active'])?'checked':''?>></label>
<div class="two-fields"><label>SERVIDOR SMTP<input name="host" required value="<?=htmlspecialchars($settings['host']??'')?>" placeholder="mail.tudominio.cl"></label><label>PUERTO<input name="port" type="number" min="1" max="65535" required value="<?=(int)($settings['port']??587)?>"></label></div>
<label>CIFRADO<select name="encryption"><option value="tls" <?=($settings['encryption']??'tls')==='tls'?'selected':''?>>STARTTLS · recomendado, puerto 587</option><option value="ssl" <?=($settings['encryption']??'')==='ssl'?'selected':''?>>SSL/TLS directo · puerto 465</option><option value="none" <?=($settings['encryption']??'')==='none'?'selected':''?>>Sin cifrado</option></select></label>
<label>USUARIO SMTP<input name="username" value="<?=htmlspecialchars($settings['username']??'')?>" autocomplete="off" placeholder="pedidos@tudominio.cl"></label><label>CONTRASEÑA SMTP<input name="password" type="password" autocomplete="new-password" placeholder="<?=empty($settings['password'])?'Ingresa la contraseña':'•••••••••••• · dejar vacío para conservar'?>"><small>La contraseña queda cifrada y nunca vuelve a mostrarse.</small></label>
<div class="two-fields"><label>CORREO REMITENTE<input name="from_email" type="email" required value="<?=htmlspecialchars($settings['from_email']??'')?>"></label><label>NOMBRE DEL REMITENTE<input name="from_name" required value="<?=htmlspecialchars($settings['from_name']??'Ultra Media Digital')?>"></label></div><label>RESPONDER A<input name="reply_to" type="email" required value="<?=htmlspecialchars($settings['reply_to']??'')?>"></label>
<div class="smtp-test"><label>ENVIAR PRUEBA A<input name="test_email" type="email" placeholder="tu-correo@dominio.cl"></label><button class="btn btn-secondary" name="action" value="test">GUARDAR Y ENVIAR PRUEBA</button></div><button class="btn btn-primary" name="action" value="save">GUARDAR CONFIGURACIÓN →</button></form>
<aside class="panel gateway-guide"><span class="eyebrow">AYUDA</span><h2>DATOS HABITUALES DE CPANEL</h2><div><b>SERVIDOR</b><strong>mail.tudominio.cl</strong></div><div><b>PUERTO TLS</b><strong>587</strong></div><div><b>PUERTO SSL</b><strong>465</strong></div><div><b>USUARIO</b><strong>CORREO COMPLETO</strong></div><article><b>SMTP ENVÍA · IMAP RECIBE</b><p>Para pedidos y notificaciones se necesita SMTP. IMAP solo se utiliza cuando una aplicación debe leer mensajes recibidos.</p></article><article><b>ANTES DE ACTIVAR</b><p>Crea la cuenta en cPanel, guarda la configuración y utiliza “Guardar y enviar prueba”.</p></article></aside></div></div>
