CREATE TABLE IF NOT EXISTS email_settings(
 id TINYINT UNSIGNED PRIMARY KEY,
 active TINYINT(1) NOT NULL DEFAULT 0,
 host VARCHAR(190) NOT NULL,
 port SMALLINT UNSIGNED NOT NULL DEFAULT 587,
 encryption ENUM('tls','ssl','none') NOT NULL DEFAULT 'tls',
 username VARCHAR(190) NOT NULL,
 password_encrypted TEXT NOT NULL,
 from_email VARCHAR(190) NOT NULL,
 from_name VARCHAR(160) NOT NULL DEFAULT 'Ultra Media Digital',
 reply_to VARCHAR(190) NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
