ALTER TABLE photos
  ADD COLUMN IF NOT EXISTS watermark_scale TINYINT UNSIGNED NOT NULL DEFAULT 90 AFTER watermark_text,
  ADD COLUMN IF NOT EXISTS watermark_opacity TINYINT UNSIGNED NOT NULL DEFAULT 65 AFTER watermark_scale;
