ALTER TABLE photos
  ADD COLUMN watermark_scale TINYINT UNSIGNED NOT NULL DEFAULT 90 AFTER watermark_text;

ALTER TABLE photos
  ADD COLUMN watermark_opacity TINYINT UNSIGNED NOT NULL DEFAULT 65 AFTER watermark_scale;
