<?php
namespace App\Controllers;
use App\Core\Database;
final class AdminController{
 public function dashboard():void{$db=Database::db();$stats=['sales'=>(int)$db->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE status='paid'")->fetchColumn(),'orders'=>(int)$db->query("SELECT COUNT(*) FROM orders WHERE status='paid'")->fetchColumn(),'photos'=>(int)$db->query('SELECT COUNT(*) FROM photos')->fetchColumn(),'storage'=>(int)$db->query('SELECT COALESCE(SUM(file_size),0) FROM photos')->fetchColumn()];$daily=$db->query("SELECT DATE(paid_at) day,SUM(total) total FROM orders WHERE paid_at>=DATE_SUB(CURDATE(),INTERVAL 13 DAY) GROUP BY DATE(paid_at) ORDER BY day")->fetchAll();view('admin/dashboard',compact('stats','daily'));}
 public function photos():void{$db=Database::db();$events=$db->query('SELECT * FROM events ORDER BY event_date DESC')->fetchAll();$photos=$db->query('SELECT p.*,e.name event_name FROM photos p JOIN events e ON e.id=p.event_id ORDER BY p.id DESC LIMIT 100')->fetchAll();view('admin/photos',compact('events','photos'));}
 public function upload():never{verify_csrf();$event=(int)($_POST['event_id']??0);$watermark=isset($_POST['watermark']);$files=$_FILES['photos']??null;if(!$event||!$files)redirect('/admin/fotos');foreach($files['tmp_name'] as $k=>$tmp){if($files['error'][$k]!==UPLOAD_ERR_OK||!@getimagesize($tmp))continue;$ext=strtolower(pathinfo($files['name'][$k],PATHINFO_EXTENSION));if(!in_array($ext,['jpg','jpeg','png','webp'],true))continue;$base=bin2hex(random_bytes(10)).'.'.$ext;$orig='storage/originals/'.$base;$preview='storage/previews/'.$base;move_uploaded_file($tmp,ROOT.'/'.$orig);$this->preview(ROOT.'/'.$orig,ROOT.'/'.$preview,$watermark);$s=Database::db()->prepare("INSERT INTO photos(event_id,title,bib_number,price,original_path,preview_path,file_size,watermark_enabled,download_enabled,status) VALUES(?,?,?,?,?,?,?,?,?,'active')");$s->execute([$event,pathinfo($files['name'][$k],PATHINFO_FILENAME),trim($_POST['bib_number']??''),(int)($_POST['price']??4990),$orig,$preview,filesize(ROOT.'/'.$orig),$watermark?1:0,isset($_POST['download_enabled'])?1:0]);}redirect('/admin/fotos');}
 public function toggleDownload():never{verify_csrf();$s=Database::db()->prepare('UPDATE photos SET download_enabled=? WHERE id=?');$s->execute([(int)($_POST['enabled']??0),(int)($_POST['id']??0)]);redirect('/admin/fotos');}
 private function preview(string $src,string $dest,bool $wm):void{$info=getimagesize($src);$create=match($info[2]){IMAGETYPE_JPEG=>'imagecreatefromjpeg',IMAGETYPE_PNG=>'imagecreatefrompng',IMAGETYPE_WEBP=>'imagecreatefromwebp',default=>null};if(!$create){copy($src,$dest);return;}$im=$create($src);$w=imagesx($im);$h=imagesy($im);$nw=min($w,1600);$nh=(int)($h*$nw/$w);$out=imagecreatetruecolor($nw,$nh);imagecopyresampled($out,$im,0,0,0,0,$nw,$nh,$w,$h);if($wm){$white=imagecolorallocatealpha($out,255,255,255,55);for($y=120;$y<$nh;$y+=260)for($x=-100;$x<$nw;$x+=440)imagestring($out,5,$x,$y,'ULTRA MEDIA DIGITAL',$white);}imagejpeg($out,$dest,82);imagedestroy($im);imagedestroy($out);}
}

