<?php
namespace App\Controllers;
use App\Core\Database;use App\Models\Photo;use App\Services\FlowClient;use Throwable;
final class CheckoutController{
 public function index():void{$photos=Photo::ids($_SESSION['cart']??[]);view('store/checkout',['photos'=>$photos,'pageTitle'=>'Finalizar compra | Ultra','flowPage'=>true,'bodyClass'=>'inner','toplineLeft'=>'CHECKOUT SEGURO','toplineRight'=>'PAGO PROCESADO POR FLOW']);}
 public function process():never{
  verify_csrf();$photos=Photo::ids($_SESSION['cart']??[]);if(!$photos)redirect('/carrito');$email=filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL);if(!$email){$_SESSION['error']='Ingresa un correo válido';redirect('/checkout');}
  $total=(int)array_sum(array_column($photos,'price'));if($total<350){$_SESSION['error']='El total mínimo permitido por Flow es $350.';redirect('/checkout');}$db=Database::db();$db->beginTransaction();
  try{$downloadToken=bin2hex(random_bytes(24));$s=$db->prepare("INSERT INTO orders(customer_name,customer_email,phone,rut,total,status,payment_provider,download_token) VALUES(?,?,?,?,?,'pending','flow',?)");$s->execute([trim($_POST['name']??'Cliente'),$email,trim($_POST['phone']??''),trim($_POST['rut']??''),$total,$downloadToken]);$oid=(int)$db->lastInsertId();$item=$db->prepare('INSERT INTO order_items(order_id,photo_id,unit_price) VALUES(?,?,?)');foreach($photos as $p)$item->execute([$oid,$p['id'],$p['price']]);$db->commit();
   $result=(new FlowClient())->createPayment(['id'=>$oid,'commerce_order'=>'UMD'.$oid,'subject'=>'Fotografías deportivas Ultra Media · Pedido UMD-'.$oid,'amount'=>$total,'email'=>$email,'confirmation_url'=>url('pago/flow/confirmacion'),'return_url'=>url('pago/flow/retorno')]);
   if(empty($result['url'])||empty($result['token'])||empty($result['flowOrder']))throw new \RuntimeException('Flow no entregó una URL de pago válida.');$db->prepare('UPDATE orders SET payment_reference=? WHERE id=?')->execute([(string)$result['flowOrder'],$oid]);header('Location: '.$result['url'].'?token='.rawurlencode((string)$result['token']),true,303);exit;
  }catch(Throwable $e){if($db->inTransaction())$db->rollBack();if(isset($oid))$db->prepare("UPDATE orders SET status='failed' WHERE id=? AND status='pending'")->execute([$oid]);error_log('Flow create: '.$e->getMessage());$_SESSION['error']='No fue posible iniciar el pago con Flow. Revisa la configuración o inténtalo nuevamente.';redirect('/checkout');}
 }
 public function confirmation():void{
  $token=trim((string)($_POST['token']??''));if($token===''){http_response_code(400);echo 'TOKEN_REQUIRED';return;}
  try{$this->synchronize($token);http_response_code(200);echo 'OK';}catch(Throwable $e){error_log('Flow confirmation: '.$e->getMessage());http_response_code(500);echo 'RETRY';}
 }
 public function paymentReturn():never{
  $token=trim((string)($_POST['token']??$_GET['token']??''));if($token===''){$_SESSION['payment_error']='Flow no entregó el identificador de la transacción.';redirect('/pago/resultado');}
  try{$order=$this->synchronize($token);if($order['status']==='paid'){$_SESSION['cart']=[];redirect('/gracias?token='.$order['download_token']);}$_SESSION['payment_order']=$order['id'];$_SESSION['payment_state']=$order['status'];}catch(Throwable $e){error_log('Flow return: '.$e->getMessage());$_SESSION['payment_error']='No pudimos consultar todavía el resultado del pago.';}redirect('/pago/resultado');
 }
 public function result():void{$order=null;if(!empty($_SESSION['payment_order'])){$s=Database::db()->prepare('SELECT * FROM orders WHERE id=?');$s->execute([(int)$_SESSION['payment_order']]);$order=$s->fetch();}view('store/payment-result',['order'=>$order,'error'=>$_SESSION['payment_error']??null,'pageTitle'=>'Estado del pago | Ultra','flowPage'=>true,'bodyClass'=>'inner','toplineLeft'=>'ESTADO DEL PAGO','toplineRight'=>'FLOW']);unset($_SESSION['payment_error']);}
 public function thanks():void{$token=$_GET['token']??'';$s=Database::db()->prepare("SELECT o.*,p.id photo_id,p.title FROM orders o JOIN order_items i ON i.order_id=o.id JOIN photos p ON p.id=i.photo_id WHERE o.download_token=? AND o.status='paid'");$s->execute([$token]);$items=$s->fetchAll();view('store/thanks',['items'=>$items,'token'=>$token,'pageTitle'=>'Compra aprobada | Ultra','flowPage'=>true,'bodyClass'=>'success','hideChrome'=>true]);}
 private function synchronize(string $token):array{
  $status=(new FlowClient())->getStatus($token);$commerce=(string)($status['commerceOrder']??'');if(!preg_match('/^UMD(\d+)$/',$commerce,$match))throw new \RuntimeException('Orden Flow inválida.');$db=Database::db();$s=$db->prepare('SELECT * FROM orders WHERE id=? AND payment_provider=\'flow\'');$s->execute([(int)$match[1]]);$order=$s->fetch();if(!$order)throw new \RuntimeException('Pedido local no encontrado.');if((int)($status['amount']??-1)!==(int)$order['total']||($status['currency']??'')!=='CLP')throw new \RuntimeException('Monto o moneda no coincide.');$flowState=(int)($status['status']??0);if($order['status']!=='paid'){if($flowState===2)$db->prepare("UPDATE orders SET status='paid',paid_at=NOW(),payment_reference=? WHERE id=?")->execute([(string)($status['flowOrder']??$order['payment_reference']),$order['id']]);elseif(in_array($flowState,[3,4],true))$db->prepare("UPDATE orders SET status='failed',payment_reference=? WHERE id=? AND status<>'paid'")->execute([(string)($status['flowOrder']??$order['payment_reference']),$order['id']]);} $s->execute([(int)$match[1]]);return $s->fetch();
 }
}
