<?php
namespace App\Controllers;
use App\Core\Database;use App\Models\Customer;use App\Models\ShopCart;use App\Services\FlowClient;use Throwable;
final class CheckoutController{
 public function index():void{$items=ShopCart::items();if(!$items)redirect('/carrito');view('store/checkout',['items'=>$items,'customer'=>customer_user(),'pageTitle'=>'Finalizar compra | Ultra','flowPage'=>true,'bodyClass'=>'inner','toplineLeft'=>'CHECKOUT SEGURO','toplineRight'=>'PAGO PROCESADO POR FLOW']);}
 public function process():never{verify_csrf();$items=ShopCart::items();if(!$items)redirect('/carrito');$email=filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL);if(!$email){$_SESSION['error']='Ingresa un correo válido';redirect('/checkout');}$db=Database::db();$customer=customer_user();if(!$customer&&isset($_POST['create_account'])){$existing=Customer::email($email);if($existing){$_SESSION['error']='Ya existe una cuenta con ese correo. Inicia sesión antes de comprar para asociar el pedido.';redirect('/mi-cuenta/login');}$password=$_POST['account_password']??'';if(strlen($password)<8){$_SESSION['error']='La contraseña de la cuenta debe tener al menos 8 caracteres.';redirect('/checkout');}$customer=Customer::create(['name'=>trim($_POST['name']??'Cliente'),'email'=>$email,'password'=>$password,'phone'=>trim($_POST['phone']??''),'rut'=>trim($_POST['rut']??'')]);$_SESSION['customer_user']=$customer;}$total=array_sum(array_column($items,'price'));if($total<350){$_SESSION['error']='El total mínimo permitido por Flow es $350.';redirect('/checkout');}$db->beginTransaction();try{$downloadToken=bin2hex(random_bytes(24));$s=$db->prepare("INSERT INTO orders(customer_id,customer_name,customer_email,phone,rut,total,status,payment_provider,download_token) VALUES(?,?,?,?,?,?,'pending','flow',?)");$s->execute([$customer['id']??null,trim($_POST['name']??$customer['name']??'Cliente'),$email,trim($_POST['phone']??''),trim($_POST['rut']??''),$total,$downloadToken]);$oid=(int)$db->lastInsertId();$q=$db->prepare('INSERT INTO order_items(order_id,photo_id,set_id,item_type,item_title,selected_photo_ids,unit_price) VALUES(?,?,?,?,?,?,?)');foreach($items as $i)$q->execute([$oid,$i['photo_id'],$i['set_id'],$i['type'],$i['title'],$i['type']==='pack'?json_encode($i['selected_photo_ids']):null,$i['price']]);$db->commit();$result=(new FlowClient())->createPayment(['id'=>$oid,'commerce_order'=>'UMD'.$oid,'subject'=>'Fotografías deportivas Ultra Media · Pedido UMD-'.$oid,'amount'=>$total,'email'=>$email,'confirmation_url'=>url('pago/flow/confirmacion'),'return_url'=>url('pago/flow/retorno')]);if(empty($result['url'])||empty($result['token'])||empty($result['flowOrder']))throw new \RuntimeException('Flow no entregó una URL válida.');$db->prepare('UPDATE orders SET payment_reference=? WHERE id=?')->execute([(string)$result['flowOrder'],$oid]);header('Location: '.$result['url'].'?token='.rawurlencode((string)$result['token']),true,303);exit;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if(isset($oid))$db->prepare("UPDATE orders SET status='failed' WHERE id=? AND status='pending'")->execute([$oid]);error_log('Flow create: '.$e->getMessage());$_SESSION['error']='No fue posible iniciar el pago con Flow.';redirect('/checkout');}}
 public function confirmation():void{$token=trim((string)($_POST['token']??''));if($token===''){http_response_code(400);echo'TOKEN_REQUIRED';return;}try{$this->synchronize($token);echo'OK';}catch(Throwable $e){error_log('Flow confirmation: '.$e->getMessage());http_response_code(500);echo'RETRY';}}
 public function paymentReturn():never{$token=trim((string)($_POST['token']??$_GET['token']??''));if($token===''){$_SESSION['payment_error']='Flow no entregó el identificador.';redirect('/pago/resultado');}try{$order=$this->synchronize($token);if($order['status']==='paid'){$_SESSION['cart']=[];redirect('/gracias?token='.$order['download_token']);}$_SESSION['payment_order']=$order['id'];}catch(Throwable $e){error_log('Flow return: '.$e->getMessage());$_SESSION['payment_error']='No pudimos consultar todavía el pago.';}redirect('/pago/resultado');}
 public function result():void{$order=null;if(!empty($_SESSION['payment_order'])){$s=Database::db()->prepare('SELECT * FROM orders WHERE id=?');$s->execute([$_SESSION['payment_order']]);$order=$s->fetch();}view('store/payment-result',['order'=>$order,'error'=>$_SESSION['payment_error']??null,'pageTitle'=>'Estado del pago | Ultra','flowPage'=>true,'bodyClass'=>'inner']);unset($_SESSION['payment_error']);}
 public function thanks():void{$token=$_GET['token']??'';$s=Database::db()->prepare("SELECT o.*,i.id item_id,i.item_type,i.photo_id,i.set_id,COALESCE(p.title,i.item_title,ps.name) title FROM orders o JOIN order_items i ON i.order_id=o.id LEFT JOIN photos p ON p.id=i.photo_id LEFT JOIN photo_sets ps ON ps.id=i.set_id WHERE o.download_token=? AND o.status='paid'");$s->execute([$token]);$items=$s->fetchAll();view('store/thanks',['items'=>$items,'token'=>$token,'pageTitle'=>'Compra aprobada | Ultra','flowPage'=>true,'bodyClass'=>'success','hideChrome'=>true]);}
 private function synchronize(string $token):array{$status=(new FlowClient())->getStatus($token);if(!preg_match('/^UMD(\d+)$/',(string)($status['commerceOrder']??''),$m))throw new \RuntimeException('Orden inválida.');$db=Database::db();$s=$db->prepare("SELECT * FROM orders WHERE id=? AND payment_provider='flow'");$s->execute([(int)$m[1]]);$o=$s->fetch();if(!$o||(int)($status['amount']??-1)!==(int)$o['total']||($status['currency']??'')!=='CLP')throw new \RuntimeException('Pedido, monto o moneda inválidos.');$state=(int)($status['status']??0);if($o['status']!=='paid'){if($state===2)$db->prepare("UPDATE orders SET status='paid',paid_at=NOW(),payment_reference=? WHERE id=?")->execute([(string)$status['flowOrder'],$o['id']]);elseif(in_array($state,[3,4],true))$db->prepare("UPDATE orders SET status='failed' WHERE id=? AND status<>'paid'")->execute([$o['id']]);}$s->execute([(int)$m[1]]);return $s->fetch();}
}
