<?php
namespace App\Controllers;use App\Core\Database;use App\Models\Customer;
final class CustomerController{
 public function login():void{if(customer_user())redirect('/mi-cuenta');view('customer/login',['pageTitle'=>'Acceso clientes | Ultra','flowPage'=>true,'bodyClass'=>'inner','toplineLeft'=>'PORTAL DE CLIENTES','toplineRight'=>'TUS PEDIDOS Y DESCARGAS']);}
 public function authenticate():never{verify_csrf();$c=Customer::authenticate(trim($_POST['email']??''),$_POST['password']??'');if(!$c){$_SESSION['error']='Correo o contraseña incorrectos.';redirect('/mi-cuenta/login');}session_regenerate_id(true);$_SESSION['customer_user']=$c;redirect('/mi-cuenta');}
 public function logout():never{verify_csrf();unset($_SESSION['customer_user']);session_regenerate_id(true);redirect('/');}
 public function dashboard():void{require_customer();$db=Database::db();$s=$db->prepare('SELECT o.*,COUNT(i.id) items_count FROM orders o LEFT JOIN order_items i ON i.order_id=o.id WHERE o.customer_id=? GROUP BY o.id ORDER BY o.id DESC');$s->execute([customer_user()['id']]);$orders=$s->fetchAll();view('customer/dashboard',['orders'=>$orders,'pageTitle'=>'Mi cuenta | Ultra','flowPage'=>true,'bodyClass'=>'inner account-page','toplineLeft'=>'MI CUENTA','toplineRight'=>'PEDIDOS Y DESCARGAS']);}
 public function order():void{require_customer();$db=Database::db();$s=$db->prepare('SELECT * FROM orders WHERE id=? AND customer_id=?');$s->execute([(int)($_GET['id']??0),customer_user()['id']]);$order=$s->fetch();if(!$order){http_response_code(404);exit('Pedido no encontrado');}$s=$db->prepare("SELECT i.*,COALESCE(p.title,ps.name,i.item_title) title,p.preview_path,p.id photo_id,ps.id set_id,MIN(sp.id) cover_id,MIN(sp.preview_path) set_preview FROM order_items i LEFT JOIN photos p ON p.id=i.photo_id LEFT JOIN photo_sets ps ON ps.id=i.set_id LEFT JOIN photos sp ON sp.set_id=ps.id WHERE i.order_id=? GROUP BY i.id");$s->execute([$order['id']]);view('customer/order',['order'=>$order,'items'=>$s->fetchAll(),'pageTitle'=>'Detalle pedido | Ultra','flowPage'=>true,'bodyClass'=>'inner account-page']);}
 public function password():never{verify_csrf();require_customer();$db=Database::db();$s=$db->prepare('SELECT password_hash FROM customers WHERE id=?');$s->execute([customer_user()['id']]);$hash=$s->fetchColumn();$new=$_POST['new_password']??'';if(!password_verify($_POST['current_password']??'',$hash)||strlen($new)<8){$_SESSION['error']='La contraseña actual no coincide o la nueva tiene menos de 8 caracteres.';redirect('/mi-cuenta');}$db->prepare('UPDATE customers SET password_hash=? WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),customer_user()['id']]);$_SESSION['success']='Contraseña actualizada.';redirect('/mi-cuenta');}
}
