<?php
namespace App\Controllers;use App\Core\Database;use ZipArchive;
final class DownloadController{
 public function file():never{$token=(string)($_GET['token']??'');$id=(int)($_GET['id']??0);$s=Database::db()->prepare("SELECT p.original_path,p.download_enabled FROM orders o JOIN order_items i ON i.order_id=o.id JOIN photos p ON p.id=i.photo_id WHERE o.download_token=? AND p.id=? AND i.item_type='photo' AND o.status='paid' AND o.paid_at IS NOT NULL");$s->execute([$token,$id]);$p=$s->fetch();$this->sendPhoto($p,$id);}
 public function set():never{$token=(string)($_GET['token']??'');$id=(int)($_GET['id']??0);$s=Database::db()->prepare("SELECT ps.id,ps.name FROM orders o JOIN order_items i ON i.order_id=o.id JOIN photo_sets ps ON ps.id=i.set_id WHERE o.download_token=? AND ps.id=? AND i.item_type='set' AND o.status='paid' AND o.paid_at IS NOT NULL");$s->execute([$token,$id]);$set=$s->fetch();if(!$set)$this->denied();$this->sendSet($id,$set['name']);}
 public function customerFile():never{require_customer();$item=(int)($_GET['item']??0);$s=Database::db()->prepare("SELECT i.*,o.status,p.original_path,p.download_enabled,ps.name set_name FROM order_items i JOIN orders o ON o.id=i.order_id LEFT JOIN photos p ON p.id=i.photo_id LEFT JOIN photo_sets ps ON ps.id=i.set_id WHERE i.id=? AND o.customer_id=? AND o.status='paid' AND o.paid_at IS NOT NULL");$s->execute([$item,customer_user()['id']]);$i=$s->fetch();if(!$i)$this->denied();if($i['item_type']==='set')$this->sendSet((int)$i['set_id'],$i['set_name']);$this->sendPhoto($i,(int)$i['photo_id']);}
 private function sendPhoto(array|false $p,int $id):never{$root=realpath(ROOT.'/storage/originals');$file=$p?realpath(ROOT.'/'.ltrim($p['original_path'],'/')):false;if(!$p||!$p['download_enabled']||!$root||!$file||!str_starts_with($file,$root.DIRECTORY_SEPARATOR)||!is_file($file))$this->denied();header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="ultra-fotografia-'.$id.'.'.pathinfo($file,PATHINFO_EXTENSION).'"');header('Content-Length: '.filesize($file));$this->headers();readfile($file);exit;}
 private function sendSet(int $setId,string $name):never{if(!class_exists(ZipArchive::class)){http_response_code(503);exit('El servidor debe habilitar ZipArchive para descargar sets.');}$s=Database::db()->prepare("SELECT id,original_path FROM photos WHERE set_id=? AND status='active' AND download_enabled=1");$s->execute([$setId]);$photos=$s->fetchAll();if(!$photos)$this->denied();$tmp=tempnam(sys_get_temp_dir(),'ultra-set-');$zip=new ZipArchive();if($zip->open($tmp,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)$this->denied();$root=realpath(ROOT.'/storage/originals');foreach($photos as $p){$file=realpath(ROOT.'/'.ltrim($p['original_path'],'/'));if($root&&$file&&str_starts_with($file,$root.DIRECTORY_SEPARATOR))$zip->addFile($file,'foto-'.$p['id'].'.'.pathinfo($file,PATHINFO_EXTENSION));}$zip->close();$safe=preg_replace('/[^a-z0-9-]+/i','-',strtolower($name));header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="'.$safe.'.zip"');header('Content-Length: '.filesize($tmp));$this->headers();readfile($tmp);@unlink($tmp);exit;}
 private function headers():void{header('Cache-Control: private, no-store, no-cache, must-revalidate');header('Pragma: no-cache');header('X-Content-Type-Options: nosniff');}
 private function denied():never{http_response_code(403);exit('Descarga no autorizada');}
}
